services:
  zitadel:
    restart: 'always'
    image: 'ghcr.io/zitadel/zitadel:latest'
    container_name: zitadel
    command: 'start-from-init --masterkey "${MASTER_KEY}" --tlsMode disabled'
    environment:
      - 'ZITADEL_DATABASE_POSTGRES_HOST=${ZITADEL_DATABASE_POSTGRES_HOST}'
      - 'ZITADEL_DATABASE_POSTGRES_PORT=${ZITADEL_DATABASE_POSTGRES_PORT}'
      - 'ZITADEL_DATABASE_POSTGRES_DATABASE=${ZITADEL_DATABASE_POSTGRES_DATABASE}'
      - 'ZITADEL_DATABASE_POSTGRES_USER_USERNAME=${POSTGRES_USER}'
      - 'ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=${POSTGRES_PASSWORD}'
      - 'ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=${ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE}'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=${POSTGRES_USER}'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=${POSTGRES_PASSWORD}'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=${ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE}'
      - 'ZITADEL_EXTERNALSECURE=${ZITADEL_EXTERNALSECURE}'
    depends_on:
      coderevdb:
        condition: 'service_healthy'
    ports:
      - '${ZITADEL_PORT}:${ZITADEL_PORT}'
    networks:
      - coderev

  coderevdb:
    restart: 'always'
    image: postgres:16-alpine
    container_name: coderevdb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - coderev:/var/lib/postgresql/data
    networks:
      - coderev

networks:
  coderev:

volumes:
  coderev: {}