// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.src.Modules.SolveReview.Infrastructure.Persistence;

#nullable disable

namespace backend.src.Modules.SolveReview.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SolveReviewDbContext))]
    [Migration("20250302170828_updated_entity_solve")]
    partial class updated_entity_solve
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.src.Modules.SolveReview.Domain.Entities.ParameterWeights", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("CodingTimeWeight")
                        .HasColumnType("real");

                    b.Property<float>("IsCodeCopiedWeight")
                        .HasColumnType("real");

                    b.Property<float>("LastRevisionWeight")
                        .HasColumnType("real");

                    b.Property<float>("LearningTimeWeight")
                        .HasColumnType("real");

                    b.Property<float>("RevisionCountWeight")
                        .HasColumnType("real");

                    b.Property<float>("SubmissionAttemptsWeight")
                        .HasColumnType("real");

                    b.Property<float>("ThinkingTimeWeight")
                        .HasColumnType("real");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ParameterWeights");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CodingTimeWeight = 0.15f,
                            IsCodeCopiedWeight = 0.8f,
                            LastRevisionWeight = 0.15f,
                            LearningTimeWeight = 0.2f,
                            RevisionCountWeight = 0.05f,
                            SubmissionAttemptsWeight = 0.1f,
                            ThinkingTimeWeight = 0.2f
                        });
                });

            modelBuilder.Entity("backend.src.Modules.SolveReview.Domain.Entities.Solve", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CodingTime")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCodeCopied")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastRevision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LearningTime")
                        .HasColumnType("integer");

                    b.Property<double>("Priority")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<string[]>("ProblemTags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ProblemUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RevisionCount")
                        .HasColumnType("integer");

                    b.Property<int>("SubmissionAttempts")
                        .HasColumnType("integer");

                    b.Property<float?>("TagImpact")
                        .HasColumnType("real");

                    b.Property<int>("ThinkingTime")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LastRevision");

                    b.HasIndex("Priority");

                    b.HasIndex("UserId");

                    b.ToTable("Solves");
                });

            modelBuilder.Entity("backend.src.Modules.SolveReview.Domain.Entities.TagWeights", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("TagWeight")
                        .HasColumnType("real");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TagId");

                    b.HasIndex("UserId");

                    b.ToTable("TagWeights");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            TagName = "dynamic-programming",
                            TagWeight = 0.7f
                        },
                        new
                        {
                            TagId = 2,
                            TagName = "greedy",
                            TagWeight = 0.6f
                        },
                        new
                        {
                            TagId = 3,
                            TagName = "graph-theory",
                            TagWeight = 0.65f
                        },
                        new
                        {
                            TagId = 4,
                            TagName = "tree",
                            TagWeight = 0.55f
                        },
                        new
                        {
                            TagId = 5,
                            TagName = "binary-search",
                            TagWeight = 0.5f
                        },
                        new
                        {
                            TagId = 6,
                            TagName = "sorting",
                            TagWeight = 0.45f
                        },
                        new
                        {
                            TagId = 7,
                            TagName = "recursion-backtracking",
                            TagWeight = 0.6f
                        },
                        new
                        {
                            TagId = 8,
                            TagName = "divide-and-conquer",
                            TagWeight = 0.55f
                        },
                        new
                        {
                            TagId = 9,
                            TagName = "brute-force",
                            TagWeight = 0.4f
                        },
                        new
                        {
                            TagId = 10,
                            TagName = "number-theory",
                            TagWeight = 0.6f
                        },
                        new
                        {
                            TagId = 11,
                            TagName = "combinatorics",
                            TagWeight = 0.55f
                        },
                        new
                        {
                            TagId = 12,
                            TagName = "probability",
                            TagWeight = 0.5f
                        },
                        new
                        {
                            TagId = 13,
                            TagName = "game-theory",
                            TagWeight = 0.6f
                        },
                        new
                        {
                            TagId = 14,
                            TagName = "geometry",
                            TagWeight = 0.55f
                        },
                        new
                        {
                            TagId = 15,
                            TagName = "hash-table",
                            TagWeight = 0.5f
                        },
                        new
                        {
                            TagId = 16,
                            TagName = "heap-priority-queue",
                            TagWeight = 0.55f
                        },
                        new
                        {
                            TagId = 17,
                            TagName = "stack-queue",
                            TagWeight = 0.45f
                        },
                        new
                        {
                            TagId = 18,
                            TagName = "linked-list",
                            TagWeight = 0.4f
                        },
                        new
                        {
                            TagId = 19,
                            TagName = "trie-prefix-tree",
                            TagWeight = 0.6f
                        },
                        new
                        {
                            TagId = 20,
                            TagName = "segment-tree",
                            TagWeight = 0.65f
                        },
                        new
                        {
                            TagId = 21,
                            TagName = "fenwick-tree-bit",
                            TagWeight = 0.6f
                        },
                        new
                        {
                            TagId = 22,
                            TagName = "disjoint-set-union",
                            TagWeight = 0.55f
                        },
                        new
                        {
                            TagId = 23,
                            TagName = "graph-traversal-dfs-bfs",
                            TagWeight = 0.55f
                        },
                        new
                        {
                            TagId = 24,
                            TagName = "shortest-path-dijkstra-bellman-ford-floyd-warshall",
                            TagWeight = 0.65f
                        },
                        new
                        {
                            TagId = 25,
                            TagName = "minimum-spanning-tree-prims-kruskals",
                            TagWeight = 0.6f
                        },
                        new
                        {
                            TagId = 26,
                            TagName = "topological-sorting",
                            TagWeight = 0.55f
                        },
                        new
                        {
                            TagId = 27,
                            TagName = "strongly-connected-components-scc-tarjans-kosarajus",
                            TagWeight = 0.65f
                        },
                        new
                        {
                            TagId = 28,
                            TagName = "flow-algorithms-ford-fulkerson-dinics-edmonds-karp",
                            TagWeight = 0.7f
                        },
                        new
                        {
                            TagId = 29,
                            TagName = "string-matching-kmp-rabin-karp-z-algorithm-aho-corasick",
                            TagWeight = 0.6f
                        },
                        new
                        {
                            TagId = 30,
                            TagName = "suffix-array-suffix-tree",
                            TagWeight = 0.65f
                        },
                        new
                        {
                            TagId = 31,
                            TagName = "rolling-hashing",
                            TagWeight = 0.55f
                        },
                        new
                        {
                            TagId = 32,
                            TagName = "bit-manipulation",
                            TagWeight = 0.5f
                        },
                        new
                        {
                            TagId = 33,
                            TagName = "modular-arithmetic",
                            TagWeight = 0.5f
                        },
                        new
                        {
                            TagId = 34,
                            TagName = "two-pointers",
                            TagWeight = 0.45f
                        },
                        new
                        {
                            TagId = 35,
                            TagName = "sliding-window",
                            TagWeight = 0.5f
                        },
                        new
                        {
                            TagId = 36,
                            TagName = "meet-in-the-middle",
                            TagWeight = 0.55f
                        },
                        new
                        {
                            TagId = 37,
                            TagName = "trie-optimization",
                            TagWeight = 0.6f
                        },
                        new
                        {
                            TagId = 38,
                            TagName = "implementation",
                            TagWeight = 0.4f
                        },
                        new
                        {
                            TagId = 39,
                            TagName = "constructive-algorithm",
                            TagWeight = 0.5f
                        },
                        new
                        {
                            TagId = 40,
                            TagName = "interactive-problem",
                            TagWeight = 0.55f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
